esphome:
  name: fancontrol
  includes: 
    - itho.h
  libraries: 
    - SPI
    - file:///config/esphome/itho-lib

  on_boot:
    then:
      - lambda: |-
          Idlist[0]={"51,40,61","Badkamer"};
          Idlist[1]={"73,82,11","Toilet"};
          Idlist[2]={"ID3","ID3"};
          srcID[0] = 81;
          srcID[1] = 64;
          srcID[2] = 97;
          destID[0] = 118;
          destID[1] = 36;
          destID[2] = 148;
          Mydeviceid="Homeassistant"; 

esp8266:
  board: d1_mini
  framework:
    version: recommended

wifi:
  ssid: <YOURSSID>
  password: <YOURPASSWORD>

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FALLBACK AP"
    password: "jdsh348201"

captive_portal:

# Enable logging
logger:
#  level: VERBOSE #Enable this line to find out the ID of youre remote

# Enable Home Assistant API
api:

ota:

switch:
- platform: custom
  lambda: |-
    auto fansendstandby = new FanSendOrconStandBy();
    App.register_component(fansendstandby);
    return {fansendstandby};

  switches:
    name: "FanSendStandby"

- platform: custom
  lambda: |-
    auto fansendlow = new FanSendOrconLow();
    App.register_component(fansendlow);
    return {fansendlow};

  switches:
    name: "FanSendLow"

- platform: custom
  lambda: |-
    auto fansendmedium = new FanSendOrconMedium();
    App.register_component(fansendmedium);
    return {fansendmedium};

  switches:
    name: "FanSendMedium"

- platform: custom
  lambda: |-
    auto fansendhigh = new FanSendOrconHigh();
    App.register_component(fansendhigh);
    return {fansendhigh};

  switches:
    name: "FanSendHigh"

- platform: custom
  lambda: |-
    auto fansendauto = new FanSendOrconAuto();
    App.register_component(fansendauto);
    return {fansendauto};

  switches:
    name: "FanSendAuto"

text_sensor:
- platform: custom
  lambda: |-
    auto fanrecv = new FanRecv();
    App.register_component(fanrecv);
    return {fanrecv->fanspeed,fanrecv->fantimer,fanrecv->Lastid};
  text_sensors:
    - name: "fanspeed"
      icon: "mdi:transfer"   
    - name: "fantimer"
      icon: "mdi:timer"  
    - name: "lastid"
